[package]
name = "discord_bot"
version = "0.1.0"
edition = "2018"

[build]
target = "i686-pc-windows-msvc"

[dependencies]
log-panics = "2.0.0"
serenity = "0.10.10"
futures = { version = "0.3" }
tokio = { version = "1.12.0", features = ["full"] }

[lib]
crate-type = ["cdylib"]